### PR TITLE
#187364719 Feat coverage

### PR DESCRIPTION
**Pull request by Bananayosostene**
#skills setting up continuous integration

### CODE REVIEW

**Review by Yvan-David — CHANGES_REQUESTED** [review]
Please you have changed the package.json and removed a lot of packages that are necessary you should have added your new packages without removing those you found 

you should follow the naming convention of the branch
you should squash your commits and remain with only one commit for your PR

Otherwise good Job

**Review by EricNiyo73 — APPROVED** [review]
Ready to be merged

**Review by EricNiyo73 — APPROVED** [review]
Ready to be merged

**Review by EricNiyo73 — APPROVED** [review]

**Review by Yvan-David — APPROVED** [review]

**Review by Yvan-David — COMMENTED** [review]
you edited the ts config you should edit back to how it was

**Pull request closed without merging**
